### ISSUE TITLE
GitHub API: How to Label Latest Release?

### ISSUE THREAD

**Issue by ScriptAutomate** [ScriptAutomate/aws-cfn-resource-specs#16]
Currently, the **Latest Release** in the [**Releases**](https://github.com/ScriptAutomate/aws-cfn-resource-specs/releases) tab has to be manually set via the GitHub repository webpage.

Even though each release is tied to a **tag** set with git, GitHub doesn't automatically label the latest release as **Latest Release**.

Need to investigate. This will likely require use of the GitHub API in order to set. Investigating how something like [PyGithub](https://github.com/PyGithub/PyGithub) can solve this problem would be nice.

Should also evaluate the GitHub Action **Release Drafter**: https://github.com/release-drafter/release-drafter. This could allow for the latest changelog markdown to be injected into the release documentation.

**Comment by jeshan** [comment]
In my [botostubs](https://github.com/jeshan/botostubs) project, I handle this with one curl command. It should be available in the container that runs the action right? Otherwise, I suppose you could add it in your dependency step at 
https://github.com/ScriptAutomate/aws-cfn-resource-specs/blob/master/.github/workflows/cfnspecaudit.yml#L19

Here's the script that does the job for me. Feel free to steal it:

https://github.com/jeshan/botostubs/blob/master/release.sh#L12-L16

**Comment by ScriptAutomate** [comment]
I'm closing this issue out, as this repository is no longer maintained. The repo is being archived, but others are free to fork and maintain a version if they'd like.
