### ISSUE TITLE
Add Resource Provider Schemas

### ISSUE THREAD

**Issue by eduardomourar** [ScriptAutomate/aws-cfn-resource-specs#193]
It would be very nice to track changes in the [CloudFormation resource provider schemas](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-type-schemas.html) in addition to the resource specification.

**Comment by ScriptAutomate** [comment]
Oh, interesting. This could be cool. I could use a lot of the same code over again when it comes to downloading, tracking, and versioning. I'd have to create new logic around how the diffs are done, and it looks like I could completely skip the documentation endpoint lookups because docs links aren't embedded in their json for anything.

**Comment by ScriptAutomate** [comment]
I'm closing this issue out, as this repository is no longer maintained. The repo is being archived, but others are free to fork and maintain a version if they'd like.
